#!/bin/bash
######################################################################
# Set up our credentials
#
WORKDIR=$1

DIST=natty
if [ -f /home/whitejs/.credentials ];then
. /home/whitejs/.credentials
fi
export AWS_USER=$(aws_account_number)
export AWS_ACCESS=$(aws_access_key_id)
export AWS_SECRET=$(aws_secret_access_key)

if [ -z "${WORKDIR}" ]; then
    export WORKDIR=$(mktemp -d /opt/amazon/working.XXXX)
    echo "WORKDIR is ${WORKDIR}"
fi
export IMAGE="${WORKDIR}/ubuntu.fs"
export MNTPT="${WORKDIR}/loop"

export IMGBASE=$(basename ${IMAGE})
export IMDIR=$(dirname ${IMAGE})
#
######################################################################

######################################################################
# /home/whitejs/.credentials file format
#aws_account_number(){
#    echo "<AWS_USER>"
#}
#aws_access_key_id(){
#    echo "<AWS_ACCESS_KEY_ID}>"
#}
#
#aws_secret_access_key(){
#    echo "<AWS_SECRET_ACCESS_KEY>"
#}
#
#aws_certificate(){
#cat<<EOF
#-----BEGIN CERTIFICATE-----
#...
#-----END CERTIFICATE-----
#EOF
#}
#aws_private_key(){
#cat<<EOF
#-----BEGIN PRIVATE KEY-----
#...
#-----END PRIVATE KEY-----
#EOF
#}
#
######################################################################
