#!/bin/bash
######################################################################
# Set up our credentials
#
if [ -f /home/whitejs/.credentials ];then
. /home/whitejs/.credentials
fi
export AWS_USER=$(aws_account_number)
export AWS_ACCESS=$(aws_access_key_id)
export AWS_SECRET=$(aws_secret_access_key)

export IMAGE=/opt/amazon/ubuntu.fs
export MNTPT="/mnt/loop"

export IMGBASE=$(basename ${IMAGE})
export IMDIR=$(dirname ${IMAGE})
#
######################################################################
