#!/bin/bash
######################################################################
# Set up our credentials
#
if [ -f /home/whitejs/.credentials ];then
. /home/whitejs/.credentials
fi
export AWS_USER=$(aws_account_number)
export AWS_ACCESS=$(aws_access_key_id)
export AWS_SECRET=$(aws_secret_access_key)

export IMAGE=/opt/amazon/ubuntu.fs
export MNTPT="/mnt/loop"

export IMGBASE=$(basename ${IMAGE})
export IMDIR=$(dirname ${IMAGE})
#
######################################################################

######################################################################
# /home/whitejs/.credentials file format
#aws_account_number(){
#    echo "<AWS_USER>"
#}
#aws_access_key_id(){
#    echo "<AWS_ACCESS_KEY_ID}>"
#}
#
#aws_secret_access_key(){
#    echo "<AWS_SECRET_ACCESS_KEY>"
#}
#
#aws_certificate(){
#cat<<EOF
#-----BEGIN CERTIFICATE-----
#...
#-----END CERTIFICATE-----
#EOF
#}
#aws_private_key(){
#cat<<EOF
#-----BEGIN PRIVATE KEY-----
#...
#-----END PRIVATE KEY-----
#EOF
#}
#
######################################################################
