#!/bin/bash
WORKING=$1
[ -z ${WORKING} ] && echo "working dir?" && exit
[ ${UID} -ne 0 ] && echo "be you root?" && exit
[ -z "$IMAGE" ] && export IMAGE=$(ls -1rt ${WORKING}/ubuntu.fs| tail -1)
[ ! -f "$IMAGE" ] && echo "${IMAGE} not found" &&exit;
[ ! -d "${WORKING}/loop" ] && mkdir -p ${WORKING}/loop
mount -o loop ${IMAGE} ${WORKING}/loop || exit
chroot ${WORKING}/loop || exit
umount ${WORKING}/loop || exit
